// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwBEgsL4VV1doQtZc7HWI6OedYxRTF6yU',
    appId: '1:940860913273:web:5cc6c3a60daf3e408806a8',
    messagingSenderId: '940860913273',
    projectId: 'saad-notes-app',
    authDomain: 'saad-notes-app.firebaseapp.com',
    storageBucket: 'saad-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKzCFn5b5cZKBQ96lqg8UfIzxpLR9agr8',
    appId: '1:940860913273:android:f0418a10a854ae688806a8',
    messagingSenderId: '940860913273',
    projectId: 'saad-notes-app',
    storageBucket: 'saad-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNX4vAUie00n3-cKfsjA4_t9dJQEf7ztg',
    appId: '1:940860913273:ios:980b1cf5aef4312d8806a8',
    messagingSenderId: '940860913273',
    projectId: 'saad-notes-app',
    storageBucket: 'saad-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.saad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNX4vAUie00n3-cKfsjA4_t9dJQEf7ztg',
    appId: '1:940860913273:ios:980b1cf5aef4312d8806a8',
    messagingSenderId: '940860913273',
    projectId: 'saad-notes-app',
    storageBucket: 'saad-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.saad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwBEgsL4VV1doQtZc7HWI6OedYxRTF6yU',
    appId: '1:940860913273:web:325acd7a4c9ba8488806a8',
    messagingSenderId: '940860913273',
    projectId: 'saad-notes-app',
    authDomain: 'saad-notes-app.firebaseapp.com',
    storageBucket: 'saad-notes-app.firebasestorage.app',
  );
}
